# https://numtide.github.io/devshell
[devshell]
name = "devshell"
packages = [
	"nixpkgs-fmt"
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
name = "format"
command = "nixpkgs-fmt ."
help = "Format nix files with nixpkgs-fmt"